import { Injectable } from '@angular/core';
import { pacienteDto } from '../interfaces/dtos/paciente-dto';
import { Observable, of } from 'rxjs';
import { Page } from '../interfaces/page';

@Injectable({
    providedIn: 'root'
})
export class PacienteService {
    pacientes: pacienteDto[] =
    [{
        cedula: 1,
        nombre: 'Cobbie'
      }, {
        cedula: 2,
        nombre: 'Isadore'
      }, {
        cedula: 3,
        nombre: 'Gawain'
      }, {
        cedula: 4,
        nombre: 'Red'
      }, {
        cedula: 5,
        nombre: 'Lannie'
      }, {
        cedula: 6,
        nombre: 'Kalvin'
      }, {
        cedula: 7,
        nombre: 'Ambrosi'
      }, {
        cedula: 8,
        nombre: 'Mathew'
      }, {
        cedula: 9,
        nombre: 'Clem'
      }, {
        cedula: 10,
        nombre: 'Salomo'
      }, {
        cedula: 11,
        nombre: 'Godfry'
      }, {
        cedula: 12,
        nombre: 'Gordan'
      }, {
        cedula: 13,
        nombre: 'Victoir'
      }, {
        cedula: 14,
        nombre: 'Ulick'
      }, {
        cedula: 15,
        nombre: 'Percy'
      }, {
        cedula: 16,
        nombre: 'Rowland'
      }, {
        cedula: 17,
        nombre: 'Baxie'
      }, {
        cedula: 18,
        nombre: 'Bancroft'
      }, {
        cedula: 19,
        nombre: 'Meier'
      }, {
        cedula: 20,
        nombre: 'Kiel'
      }, {
        cedula: 21,
        nombre: 'Lamont'
      }, {
        cedula: 22,
        nombre: 'Brander'
      }, {
        cedula: 23,
        nombre: 'Lou'
      }, {
        cedula: 24,
        nombre: 'Abran'
      }, {
        cedula: 25,
        nombre: 'Ramsey'
      }, {
        cedula: 26,
        nombre: 'Wat'
      }, {
        cedula: 27,
        nombre: 'Giraldo'
      }, {
        cedula: 28,
        nombre: 'Justus'
      }, {
        cedula: 29,
        nombre: 'Bran'
      }, {
        cedula: 30,
        nombre: 'Norton'
      }, {
        cedula: 31,
        nombre: 'Quinton'
      }, {
        cedula: 32,
        nombre: 'Bailie'
      }, {
        cedula: 33,
        nombre: 'Ernest'
      }, {
        cedula: 34,
        nombre: 'Leroi'
      }, {
        cedula: 35,
        nombre: 'Alistair'
      }, {
        cedula: 36,
        nombre: 'Maynard'
      }, {
        cedula: 37,
        nombre: 'Townsend'
      }, {
        cedula: 38,
        nombre: 'Jonas'
      }, {
        cedula: 39,
        nombre: 'Hillard'
      }, {
        cedula: 40,
        nombre: 'Ferrel'
      }, {
        cedula: 41,
        nombre: 'Darrell'
      }, {
        cedula: 42,
        nombre: 'Farleigh'
      }, {
        cedula: 43,
        nombre: 'Aldus'
      }, {
        cedula: 44,
        nombre: 'Alberik'
      }, {
        cedula: 45,
        nombre: 'Shelton'
      }, {
        cedula: 46,
        nombre: 'Arny'
      }, {
        cedula: 47,
        nombre: 'Alvin'
      }, {
        cedula: 48,
        nombre: 'Stefano'
      }, {
        cedula: 49,
        nombre: 'Bobbie'
      }, {
        cedula: 50,
        nombre: 'Raymond'
      }, {
        cedula: 51,
        nombre: 'Eugen'
      }, {
        cedula: 52,
        nombre: 'Glenn'
      }, {
        cedula: 53,
        nombre: 'Dallon'
      }, {
        cedula: 54,
        nombre: 'Harlin'
      }, {
        cedula: 55,
        nombre: 'Samson'
      }, {
        cedula: 56,
        nombre: 'Jorge'
      }, {
        cedula: 57,
        nombre: 'Artur'
      }, {
        cedula: 58,
        nombre: 'Bran'
      }, {
        cedula: 59,
        nombre: 'Gayle'
      }, {
        cedula: 60,
        nombre: 'Turner'
      }, {
        cedula: 61,
        nombre: 'Jonas'
      }, {
        cedula: 62,
        nombre: 'Erastus'
      }, {
        cedula: 63,
        nombre: 'Lucian'
      }, {
        cedula: 64,
        nombre: 'Osmund'
      }, {
        cedula: 65,
        nombre: 'Sig'
      }, {
        cedula: 66,
        nombre: 'Aland'
      }, {
        cedula: 67,
        nombre: 'Earlie'
      }, {
        cedula: 68,
        nombre: 'Errol'
      }, {
        cedula: 69,
        nombre: 'Kaine'
      }, {
        cedula: 70,
        nombre: 'Abraham'
      }, {
        cedula: 71,
        nombre: 'Grenville'
      }, {
        cedula: 72,
        nombre: 'Fidole'
      }, {
        cedula: 73,
        nombre: 'Alfredo'
      }, {
        cedula: 74,
        nombre: 'Jonah'
      }, {
        cedula: 75,
        nombre: 'Randal'
      }, {
        cedula: 76,
        nombre: 'Ignacio'
      }, {
        cedula: 77,
        nombre: 'Riobard'
      }, {
        cedula: 78,
        nombre: 'Valentino'
      }, {
        cedula: 79,
        nombre: 'Iggie'
      }, {
        cedula: 80,
        nombre: 'Konstantin'
      }, {
        cedula: 81,
        nombre: 'Trent'
      }, {
        cedula: 82,
        nombre: 'Ignacio'
      }, {
        cedula: 83,
        nombre: 'Antin'
      }, {
        cedula: 84,
        nombre: 'Loy'
      }, {
        cedula: 85,
        nombre: 'Darb'
      }, {
        cedula: 86,
        nombre: 'Lennie'
      }, {
        cedula: 87,
        nombre: 'Redford'
      }, {
        cedula: 88,
        nombre: 'Greggory'
      }, {
        cedula: 89,
        nombre: 'Claudius'
      }, {
        cedula: 90,
        nombre: 'Bryce'
      }, {
        cedula: 91,
        nombre: 'Nichole'
      }, {
        cedula: 92,
        nombre: 'Tallie'
      }, {
        cedula: 93,
        nombre: 'Lyle'
      }, {
        cedula: 94,
        nombre: 'Mischa'
      }, {
        cedula: 95,
        nombre: 'Allyn'
      }, {
        cedula: 96,
        nombre: 'Araldo'
      }, {
        cedula: 97,
        nombre: 'Zaccaria'
      }, {
        cedula: 98,
        nombre: 'Carroll'
      }, {
        cedula: 99,
        nombre: 'Rorke'
      }, {
        cedula: 100,
        nombre: 'Gabriel'
      }]

    constructor() { };
    
    getPaginatedDTOPaciente(page: number, size: number):Observable<Page<pacienteDto>> {
        const start= page * size;
        const end= start + size;
        const content = this.pacientes.slice(start, end);

        const paginatedData: Page<pacienteDto> = {
            content: content,
            totalElements: this.pacientes.length,
            totalPages: Math.ceil(this.pacientes.length / size),
            number: page,
            size: size
        };
        return of(paginatedData);
    }
}
